### PR TITLE
⭐️ ENH: setup non regression test for maven 

### PR DESCRIPTION
**Pull request by pcavezzan**
The non regression test is based on mvn validate on Apache Camel :smile: 

For now, it fails if mvn validate takes more than 3.75Gb

### CODE REVIEW

**Comment by pcavezzan** [comment]
@jeanbisutti  Should fix issue #8

**Comment by jeanbisutti** [comment]
Huge thanks for your great work Patrice!

Could you please have a look at the following feedbacks ?
* Could you please explain why properties can be overriden by environment variables now?
* The _MvnValidateAllocationByMaven3VersionTest_ and _MvnValidateProfilingTest_ test classes do not work any more in my computer. Here is the exception:
```
Caused by: java.lang.NumberFormatException: null
	at java.base/java.lang.Integer.parseInt(Integer.java:620)
	at java.base/java.lang.Integer.parseInt(Integer.java:776)
	at org.quickperf.maven.bench.config.BenchProperties.initializeProperties(BenchProperties.java:34)
	at org.quickperf.maven.bench.config.BenchProperties.<init>(BenchProperties.java:15)
	at org.quickperf.maven.bench.config.BenchProperties.<clinit>(BenchProperties.java:12)
	... 24 more
```
Could you please have a look?
* Could you please add a few words about this non regression test on the Readme?

One more time, huge thanks! We are close to an automatic non regression test on Maven heap allocation.

**Comment by jeanbisutti** [comment]
Hello Patrice,
Can I close this PR ? The last version is #15?

**Comment by pcavezzan** [comment]
Yes you are right @jeanbisutti, I close this one in favor of #15

**Pull request closed without merging**
